name: Node.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted   # this will target your EC2 runner

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install dependencies (Node already installed on EC2)
      - name: Install dependencies
        run: npm ci

      # 3. Run lint
      - name: Run lint
        run: npm run lint

      # 4. Run tests
      - name: Run tests
        run: npm test

      # 5. Build project
      - name: Build project
        run: npm run build

      # 6. Deploy using PM2
      - name: Deploy with PM2
        run: |
          pm2 stop my-node-app || true
          pm2 start dist/server.js --name backend-service
          pm2 save
